# Generated by Django 6.0.5 on 2026-05-26 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField()),
                ('cover_letter', models.TextField(blank=True)),
                ('ai_match_score', models.IntegerField(default=0)),
                ('ai_matched_skills', models.JSONField(default=list)),
                ('ai_missing_skills', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_strengths', models.JSONField(default=list)),
                ('ai_gaps', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='under_review', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-ai_match_score'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
